### ISSUE TITLE
Support for vegetarian/vegan classification for Studentenwerk Frankfurt

### ISSUE THREAD

**Issue by Lesik** [gsauthof/openmensa#1]
Hey,

currently the meals from Studentenwerk Frankfurt don't show whether a meal is vegetarian or vegan ([example](http://openmensa.org/api/v2/canteens/211/days/2017-11-09/meals)).

This information can be found by parsing the `title` attribute of the `<img>` of a meal. The following values are used (possibly more): vegetarisch, Vegan, Alkohol, Rind, Schwein, MSC-Fisch. Some meals have several classifications, others have no `<img>` tag at all.

Please include functionality for parsing this information so I can use it in the OpenMensa API. Thank you :)

**Comment by gsauthof** [comment]
Ok - looking at the latest [openmensa XSD](http://openmensa.org/open-mensa-v2.xsd) I would add those values as additional `note` elements under `meal`.

It seems that the format doesn't provide something more specialized for this kind of information.

**Comment by Lesik** [comment]
Yes, I also found no field that is specifically for marking a meal vegan or vegetarian – unfortunately. An entry in `note` must suffice, then.

Thank you.

**Comment by gsauthof** [comment]
The next openmensa.org parser requests should get the changed feed - i.e. starting with Monday.
